# Generated by Django 6.0.2 on 2026-02-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_payment_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="name_paid_product",
        ),
    ]
