# Generated by Django 6.0.2 on 2026-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_payment_name_paid_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(blank=True, max_length=600, null=True, verbose_name="Ссылка на оплату"),
        ),
    ]
