# Generated by Django 6.0.2 on 2026-02-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Курс")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default="materials/preview/default_prev.png",
                        null=True,
                        upload_to="materials/preview/",
                        verbose_name="Превью курса",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название урока"),
                ),
                ("description", models.TextField(verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default="materials/preview/default_prev.png",
                        null=True,
                        upload_to="materials/preview/",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="Ссылка на видео"),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
